import { useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api, type ClassRoom, type Homework, type Quiz, type QuizAttempt } from '../../lib/api'

export function TeacherQuizzes() {
  const queryClient = useQueryClient()
  const [classroomId, setClassroomId] = useState<number | ''>('')
  const [homeworkId, setHomeworkId] = useState<number | ''>('')
  const [numQuestions, setNumQuestions] = useState(15)
  const [expandedQuiz, setExpandedQuiz] = useState<number | null>(null)

  const { data: classes } = useQuery({
    queryKey: ['classes'],
    queryFn: async () => (await api.get<ClassRoom[]>('/classes/')).data,
  })
  const { data: homework } = useQuery({
    queryKey: ['homework'],
    queryFn: async () => (await api.get<Homework[]>('/homework/')).data,
  })
  const { data: quizzes } = useQuery({
    queryKey: ['quizzes'],
    queryFn: async () => (await api.get<Quiz[]>('/quizzes/')).data,
  })
  const { data: attempts } = useQuery({
    queryKey: ['quiz-attempts', expandedQuiz],
    queryFn: async () => (await api.get<QuizAttempt[]>(`/quizzes/${expandedQuiz}/attempts/`)).data,
    enabled: expandedQuiz !== null,
  })

  const generateQuiz = useMutation({
    mutationFn: async () =>
      (
        await api.post('/quizzes/generate/', {
          classroom: classroomId,
          homework: homeworkId || undefined,
          num_questions: numQuestions,
        })
      ).data,
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['quizzes'] }),
  })

  function handleGenerate(e: FormEvent) {
    e.preventDefault()
    if (classroomId) generateQuiz.mutate()
  }

  const homeworkForClass = homework?.filter((h) => h.classroom === classroomId)

  return (
    <div className="max-w-3xl mx-auto p-6 space-y-8">
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
        <h2 className="text-lg font-semibold text-slate-800 mb-1">✨ Auto-generate a quiz</h2>
        <p className="text-sm text-slate-500 mb-4">
          15-20 MCQ questions generated by AI from your class's homework topics.
        </p>
        <form onSubmit={handleGenerate} className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <select
            className="border border-slate-300 rounded-md px-3 py-2 text-sm"
            value={classroomId}
            onChange={(e) => {
              setClassroomId(Number(e.target.value))
              setHomeworkId('')
            }}
          >
            <option value="">Select class...</option>
            {classes?.map((c) => (
              <option key={c.id} value={c.id}>
                {c.name}
              </option>
            ))}
          </select>
          <select
            className="border border-slate-300 rounded-md px-3 py-2 text-sm"
            value={homeworkId}
            onChange={(e) => setHomeworkId(e.target.value ? Number(e.target.value) : '')}
            disabled={!classroomId}
          >
            <option value="">All topics taught (whole class)</option>
            {homeworkForClass?.map((h) => (
              <option key={h.id} value={h.id}>
                Just: {h.topic}
              </option>
            ))}
          </select>
          <input
            type="number"
            min={5}
            max={20}
            className="border border-slate-300 rounded-md px-3 py-2 text-sm"
            value={numQuestions}
            onChange={(e) => setNumQuestions(Number(e.target.value))}
          />
          <button
            disabled={!classroomId || generateQuiz.isPending}
            className="sm:col-span-3 bg-gradient-to-r from-indigo-500 to-fuchsia-500 text-white rounded-md px-4 py-2 text-sm font-medium disabled:opacity-50"
          >
            {generateQuiz.isPending ? 'Generating with AI...' : 'Generate quiz'}
          </button>
        </form>
      </div>

      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
        <h2 className="text-lg font-semibold text-slate-800 mb-4">📝 Your quizzes</h2>
        <div className="space-y-2">
          {quizzes?.map((q) => (
            <div key={q.id} className="border border-slate-200 rounded-lg shadow-sm hover:shadow-md transition p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-medium text-slate-800 text-sm">{q.title}</p>
                  <p className="text-xs text-slate-500">
                    {q.classroom_name} · {q.question_count} questions
                  </p>
                </div>
                <button
                  onClick={() => setExpandedQuiz(expandedQuiz === q.id ? null : q.id)}
                  className="text-sm text-indigo-600 font-medium"
                >
                  {expandedQuiz === q.id ? 'Hide results' : 'View results'}
                </button>
              </div>
              {expandedQuiz === q.id && (
                <div className="mt-3 pt-3 border-t border-slate-100 space-y-1">
                  {attempts?.length === 0 && <p className="text-xs text-slate-400">No attempts yet.</p>}
                  {attempts?.map((a) => (
                    <div key={a.id} className="flex justify-between text-sm">
                      <span className="text-slate-600">{a.student_username}</span>
                      <span className="font-medium text-slate-800">
                        {a.score}/{a.total_questions}
                      </span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}
          {quizzes?.length === 0 && <p className="text-sm text-slate-400">No quizzes generated yet.</p>}
        </div>
      </div>
    </div>
  )
}
