# Generated by Django 6.1 on 2026-08-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='abandon_reason',
            field=models.TextField(blank=True),
        ),
    ]
